### ISSUE TITLE
gzip: stdin: not in gzip format error

### ISSUE THREAD

**Issue by maxxxxpower** [theonemule/untangle-filter-update#1]
Hi there. I hope you can help!

I stumbled across this and am really hoping I can get it working. I am getting an error when running the ./filterBuilder.sh command. I have attached a screenshot to help. Thanks!

![2016-10-01_12-41-14](https://cloud.githubusercontent.com/assets/17811474/19015529/6276bd98-87d4-11e6-93a5-3341c0aa61e0.png)

**Comment by theonemule** [comment]
Could you run cat db.tar.gz and post the results here?

**Comment by maxxxxpower** [comment]
Hey thanks for the fast response. Not sure what happened, but today it worked...

How can I confirm the new URLs are in the Block Sites list?

Thanks

**Comment by theonemule** [comment]
Check the output folder to see if the sites got added.

/usr/share/untangle-webfilter-init

You probably don't want to run the script everyday, as the list doesn't change that much -- but that depends on the source data you're using.

**Comment by maxxxxpower** [comment]
I just see a single file -url. I am unable to edit or open it using nano or vi. Does that mean it worked?
